### ISSUE TITLE
macos13睡眠黑屏

### ISSUE THREAD

**Issue by zdccdz** [Baio1977/Lenovo-ThinkPad-X280#1]
采用你的efi后很多问题都解决了，以前macos13系统睡眠就重启，现在可以正常睡眠，但是睡眠时间长了唤醒时黑屏，而且睡眠时间长了之后风扇会持续高速转动，请问您自己在使用时是否存在这样的问题？或者是否知道如何解决这样的问题？

**Comment by Baio1977** [comment]
關閉螢幕幾秒鐘，重新開啟它，PC就會從睡眠中醒來
在 Hackintool 中设置

Close the screen a few seconds and reopen it and the PC wakes up from sleep

![Screenshot 2023-01-16 alle 12 48 41](https://user-images.githubusercontent.com/59058746/212671512-cac7efe6-374a-42f6-8c8f-30ee4e27c73b.png)

![Screenshot 2023-01-16 alle 12 50 00](https://user-images.githubusercontent.com/59058746/212671748-ad82b020-a314-4925-9f0c-673e1ec1b18f.png)

post ioreg

**Comment by zdccdz** [comment]
ok，let me try

**Comment by Baio1977** [comment]
Also try the new EFI version 0.8.9 I made some changes that improve the functioning, in Bios you have to enable VT-D , I dropped and patched the DMAR table.

![Screenshot 2023-01-17 alle 09 45 31](https://user-images.githubusercontent.com/59058746/212850784-117e4598-4b1f-4e78-a6a7-826503f04977.png)

**Comment by zdccdz** [comment]
ok

**Comment by zdccdz** [comment]
i used the new efi,it's ok,but i have a problem，my computer have touchscreen，when i get the kext（voodooi2c.kext and  voodooi2chid.kext）,the touchscreen work ok ,the computer sleep is ok,but the computer wake up is reboot .if no the kext, the computer wake up is ok.

**Comment by Baio1977** [comment]
If you want help I need Ioreg of your Hack and then I will try to correct the problem

**Comment by zdccdz** [comment]
i sent ioreg to you email，this is my first time get it，if it's wrong，you can tell me how to get it，thanks

**Comment by zdccdz** [comment]
please give me an email

**Comment by Baio1977** [comment]
post ioreg here

**Comment by zdccdz** [comment]
[Uploading MacBook Pro.zip…]()

**Comment by zdccdz** [comment]
[MacBook Pro.zip](https://github.com/Baio1977/Lenovo-ThinkPad-X280/files/10473400/MacBook.Pro.zip)

**Comment by Baio1977** [comment]
Touchscreen is under XHC HS10, it doesn't seem to work well, maybe on Ventura there are problems with these devices...
I'll let you know and let you know

![Screenshot 2023-01-22 alle 01 46 04](https://user-images.githubusercontent.com/59058746/213895575-e4c37248-c4d1-4597-a743-b9468af18246.png)

**Comment by Baio1977** [comment]
https://drive.google.com/drive/folders/1OAqs1G5R8lKfSJLAag4AY-jTqEBGw_Fw?usp=share_link

Test this EFI in USB , if start post NEW ioreg.

**Comment by zdccdz** [comment]
[MacBook Pro1.zip](https://github.com/Baio1977/Lenovo-ThinkPad-X280/files/10474217/MacBook.Pro1.zip)
it's start ok , this is new ioreg ,touchscreen is work ,but the computer wake is reboot too

**Comment by Baio1977** [comment]
Now the Touch works well, let's fix it further your X280
![Screenshot 2023-01-22 alle 16 43 34](https://user-images.githubusercontent.com/59058746/213924894-782ea821-3ea8-473c-9b89-d9853e92decd.png)

**Comment by zdccdz** [comment]
thank you

**Comment by zdccdz** [comment]
can you hlep to fixt the problem when  touchscreen work ,the computer wake reboot?

**Comment by Baio1977** [comment]
I have to understand the problem well, I can say that I2C via USB on Ventura have problems, when restarting system error and KP warning.
So the solution is to disable these devices.
If you want to use your USB-connected I2C devices without problems, you need to switch to Monterey

**Comment by zdccdz** [comment]
thank you
