### ISSUE TITLE
Network is slow

### ISSUE THREAD

**Issue by alexander-potemkin** [Baio1977/Lenovo-ThinkPad-X280#2]
Thank you very much for your work and repository!

I was able to set up Ventura on my x280 with some help (as my specs are slightly different), but I now have a problem that the network is quite slow - I guess it's because the Intel WiFi is not something that is supported by MacOS out of the box.

To put it more specifically, opening a news.google.com page takes like 11 seconds, while the same page on the same Ventura connected to the same WiFi takes 4 seconds max.

Is there something I can do about it or it's something to live with on Hackintosh?

Thanks in advance!

**Comment by Baio1977** [comment]
The wi fi kext is still in beta for Ventura. We are waiting for the stable version of the kext and we thank these guys, as Intel wi-fi have been NOT compatible with Hackintosh for years.

**Comment by alexander-potemkin** [comment]
Thank you, @Baio1977 ! And thanks to the guys doing the work to make Intel WiFi adapters to work, indeed!

Did I get it right, that I shall downgrade to / re-install Monterey to make sure it works fine?

I don't mind, just wanted to confirm if I got it correct :)

**Comment by Baio1977** [comment]
On monterey the Intel wi fi kext should work better.

**Comment by alexander-potemkin** [comment]
Thank you. I tried the EFI from this repository with Monterey's USB Stick and it just crashes (reboots immediately) when I try to connect to WiFi (both 2.4Ghz & 5Ghz).

May I ask you for help on this, please, @Baio1977 ?
I would understand if not, but I would highly appreciate any hints or suggestions!

**Comment by Baio1977** [comment]
https://drive.google.com/drive/folders/1gv2C5sEzqyMd6IDaNV8PNSRITy091N_x?usp=share_link test this efi for montery , if start ioreg

**Comment by alexander-potemkin** [comment]
Thanks a lot! Specially thank you for spending your time making a dedicated EFI for me, much appreciate it!!!

With your working EFI and your pointings to the right direction, I realised that I might need to better settle with a more battle tested `itlwm` driver, which I did and it works more or less fine now.

More or less is because when my laptop is exactly next to the WiFi router or a bit far from it - it works with issues, works best of all when it's on a moderate distance.

I've got another issue on my hand now... I understand that it might be another topic altogether, please, let me know if it has to be done in a separate issue or if you don't have any capacity for it - I would well understand it!

My issue now is with Bluetooth - it doesn't work from time to time after the MacOS (Monterey) sleep - only OS reboot helps.

Did you have anything like that? I've tried to add `IntelBTPatcher` - just rebooted with this kext, will see if it helps, but wonder if you heard anything...

And one more thing: didn't you consider to buy BCM943602 or BCM94350 and replace an intel module? It seems like cost not that much and from what I understand will resolve both WiFi and Bluetooth issues... Unless I'm missing something?

Thanks in advance anyway!!

**Comment by Baio1977** [comment]
Replacement with native WI-FI combo is best

**Comment by alexander-potemkin** [comment]
You mean some of the Broadcom chips, like BCM943602 or BCM94350 mentioned above?

**Comment by Baio1977** [comment]
I don't know if lenovo still has whitlist in knowledgeable bios by searching on the net.

**Comment by alexander-potemkin** [comment]
Thanks a lot for all your help and assistance, I really appreciate it!

I ended up switching my Lenovo laptop to (Linux based) PopOS and couldn't be happier about it's hardware support and software seems to be Ok.

I very much appreciate your support - this experience was very valuable and important for me!

**Comment by Baio1977** [comment]
I'm trying to understand how YogaSMC works at the ACPI level.
I've had these Thinkpads:
X280 Kabylake -r , X1 Tablet Kabylake -r , T480 Kabylake and T14 CometLake.Where I can get the best keyboard functionality is T14 I am attaching photos and file DSDT

[DSDT_T14.aml.zip](https://github.com/Baio1977/Lenovo-ThinkPad-X280/files/10950619/DSDT_T14.aml.zip)
![Screenshot 2023-03-12 alle 11 49 55](https://user-images.githubusercontent.com/59058746/224539841-3157e352-2e3a-47ad-9027-ebceabc0df70.png)

On T480 X280 and X1Tablet 3Gen instead the keyboard does not respond as it should and many FN keys have no function

[DSDT_X1 Tablet.aml.zip](https://github.com/Baio1977/Lenovo-ThinkPad-X280/files/10950624/DSDT_X1.Tablet.aml.zip)

![Screenshot 2023-03-12 alle 11 53 14](https://user-images.githubusercontent.com/59058746/224539984-23b82413-bbf2-47b5-b018-d224e15f1060.png)
