### ISSUE TITLE
Scale resolution?

### ISSUE THREAD

**Issue by alexander-potemkin** [Baio1977/Lenovo-ThinkPad-X280#3]
I love the work you did more and more. One more question, hope it's alright: didn't you consider to implement screen resolution scaling?

I did it on Linux, it makes this monitor shine. I've found that it seems to be possible ([guide](https://github.com/bbhardin/A-Guide-to-MacOS-Scaled-Resolutions) and [another one](http://x220.mcdonnelltech.com/enable-scaled-resolutions/)), but my skills are somehow lucking here.

**Comment by Baio1977** [comment]
Hackintool
![Screenshot 2023-02-12 alle 23 38 22](https://user-images.githubusercontent.com/59058746/218341490-fd2c4ead-7525-4dca-bec7-14666f8c60dd.png)

**Comment by alexander-potemkin** [comment]
Thank you!!

Please, forgive my ignorance - I tried to find it myself and google it, but didn't find that: my Hackintool settings are not preserved. I guess what I should do, it's to load the config.plist and then save it somehow?

**Comment by Baio1977** [comment]
https://github.com/xzhih/one-key-hidpi

**Comment by alexander-potemkin** [comment]
Thank you! That's exactly what I found as well :)
