### ISSUE TITLE
external output 4k 60hz not working

### ISSUE THREAD

**Issue by yjkddlt** [Baio1977/Lenovo-ThinkPad-X280#4]
typec to dp：can only work up to 2k

**Comment by Baio1977** [comment]
In order to generate 4K signal, DVMT Bios option 64\96 or 128 would be needed, but the Lenovo bios are locked.

**Comment by Baio1977** [comment]
https://github.com/Baio1977/Lenovo-Thinkpad-T14/issues/4#issuecomment-1464904727
