### ISSUE TITLE
a problem about macOS update

### ISSUE THREAD

**Issue by zdccdz** [Baio1977/Lenovo-ThinkPad-X280#5]
hi，my computer have two ssd ,the one is original computer,the another is install on 4g card by myself. my macos install on the second ssd，open computer by oc on the original ssd. since the bigsur  beta 4，the macOS update can‘t  accomplis， i must change install the second ssd to original ssd ，then macOS update can accomplish. Do you know how to update macOS on the second ssd ，not change install ssd，thank you！

**Comment by Baio1977** [comment]
when you have problems with Update update from Full installer , I do it all the time , working 100%

**Comment by zdccdz** [comment]
i will try next time，use your efi i no update

**Comment by zdccdz** [comment]
i update from full installer，it can't complete，i not by -v model，so i don't know the problem，your system install on second ssd？

**Comment by Baio1977** [comment]
Disable Bluetoolfixup.kext . test

**Comment by zdccdz** [comment]
ok，i will try
